| Time Zone | Cmd Command
| --- | --- |
| UTC+00:00 | tzutil /s "GMT Standard Time"
| UTC+01:00 | tzutil /s "W. Europe Standard Time"
| UTC+02:00 | tzutil /s "E. Europe Standard Time"
| UTC+03:00 | tzutil /s "Arab Standard Time"
| UTC+03:30 | tzutil /s "Iran Standard Time"
| UTC+04:00 | tzutil /s "Arabian Standard Time"
| UTC+04:30 | tzutil /s "Afghanistan Standard Time"
| UTC+05:00 | tzutil /s "West Asia Standard Time"
| UTC+05:30 | tzutil /s "India Standard Time"
| UTC+06:00 | tzutil /s "Central Asia Standard Time"
| UTC+06:30 | tzutil /s "Myanmar Standard Time"
| UTC+07:00 | tzutil /s "SE Asia Standard Time"
| UTC+08:00 | tzutil /s "China Standard Time"
| UTC+08:45 | tzutil /s "Aus Central W. Standard Time"
| UTC+09:00 | tzutil /s "Tokyo Standard Time"
| UTC+09:30 | tzutil /s "Cen. Australia Standard Time"
| UTC+10:00 | tzutil /s "AUS Eastern Standard Time"
| UTC+10:30 | tzutil /s "Lord Howe Standard Time"
| UTC+11:00 | tzutil /s "UTC+11"
| UTC+12:00 | tzutil /s "New Zealand Standard Time"
| UTC+12:45 | tzutil /s "Chatham Islands Standard Time"
| UTC-12:00 | tzutil /s "Dateline Standard Time"
| UTC-11:00 | tzutil /s "UTC-11"
| UTC-10:00 | tzutil /s "Hawaiian Standard Time"
| UTC-09:30 | tzutil /s "Marquesas Standard Time"
| UTC-09:00 | tzutil /s "Alaskan Standard Time"
| UTC-08:00 | tzutil /s "Pacific Standard Time"
| UTC-07:00 | tzutil /s "Mountain Standard Time"
| UTC-06:00 | tzutil /s "Central America Standard Time"
| UTC-05:00 | tzutil /s "Eastern Standard Time"
| UTC-04:30 | tzutil /s "Venezuela Standard Time"
| UTC-04:00 | tzutil /s "Atlantic Standard Time"
| UTC-03:30 | tzutil /s "Newfoundland Standard Time"
| UTC-03:00 | tzutil /s "SA Eastern Standard Time"
| UTC-02:00 | tzutil /s "UTC-02"
| UTC-01:00 | tzutil /s "Cape Verde Standard Time"
